name: Build and Release EdgeSavedPasswordsDumper

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Solution
        run: |
          msbuild EdgeSavedPasswordsDumper/EdgeSavedPasswordsDumper.sln /p:Configuration=Release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref_name }}
          files: |
            EdgeSavedPasswordsDumper/bin/Release/EdgeSavedPasswordsDumper.exe
            EdgeSavedPasswordsDumper/bin/Release/EdgeSavedPasswordsDumper.exe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip the Executable
        run: |
          Compress-Archive -Path EdgeSavedPasswordsDumper/bin/Release/EdgeSavedPasswordsDumper.exe -DestinationPath EdgeSavedPasswordsDumper/bin/Release/EdgeSavedPasswordsDumper-${{ github.ref_name }}.zip
